name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: IvanJosipovic/KubernetesCRDModelGen/.github/workflow-templates/update.yaml@alpha